title: Match Report Generator | whdzera
username: whdzera
email: whdzera@gmail.com
baseurl: "/match-report-generator"
url: "" 
twitter_username: whdzera
github_username:  rokhimin/jekyll-match-report-generator
donate_username: whdzera
